supplier = Supplier.create!(name: "Sam Ash", email: "samash@asmash.com", phone_number: "12345678")
supplier = Supplier.create!(name: "Guitar Center", email: "guitarcenter@guitarcenter.com", phone_number: "23456789")
supplier = Supplier.create!(name: "Sweetwater", email: "sweetwater@sweetwater.com", phone_number: "34567890")

product = Product.create!(supplier_id: 1, inventory: 100, name: "Martin D-28", price: 2899, description: "2017 D-28 Dreadnought Acoustic Guitar Natural. Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined 2017 D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, Johnny Cash, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced.", available: "yes")
product = Product.create!(supplier_id: 3, inventory: 97, name: "Taylor K14ce", price: 4999, description: "This gorgeous Grand Auditorium features Hawaiian koa back and sides paired with a torrefied Sitka spruce top. The guitar was inspired by Taylor's revolutionary V-Class bracing, which boosts volume evenly across the tonal spectrum, increases sustain, and improves the natural intonation of the instrument by creating a more synergistic response from the soundboard. This fosters a more harmonious relationship between the notes you play, helping chords to ring out in cohesive splendor.", available: "yes")
product = Product.create!(supplier_id: 2, inventory: 34, name: "Guild D-55", price: 3599, description: "The D-55 remains true to all the premium appointments of its 1968 predecessor, including a AAA Sitka spruce top, solid Indian Rosewood back and sides, ebony fingerboard and bridge, and nitrocellulose finish. Internal refinements include scalloped Adirondack bracing as well as an improved dovetail neck-joint, hand fit to make this generation of D-55 the lightest, loudest, and best-sounding yet.", available: "yes")
product = Product.create!(supplier_id: 2, inventory: 13, name: "Yamaha A5R", price: 1399, description: "The A5R ARE, traditional western body cutaway guitar, features all-solid rosewood back and sides with hand-selected sitka spruce top with Yamaha's original A.R.E. wood-torrefaction technology. Natural, dynamic plugged-in tone from the SRT2 pickup system perfectly suit your performance on the stage and the made-in-Japan premium build quality will gratify advanced players' desire.", available: "no")

image = Image.create!(url: "https://images-na.ssl-images-amazon.com/images/I/6144VPBpyyL._AC_SL1200_.jpg", product_id: 1)
image = Image.create!(url: "https://d1aeri3ty3izns.cloudfront.net/media/41/419498/600/preview.jpg", product_id: 2)
image = Image.create!(url: "https://images.reverb.com/image/upload/s--4PeayuD2--/t_card-square/v1592613263/t4wy5hcmsmmrswsatzzj.jpg", product_id: 3)
image = Image.create!(url: "https://images.reverb.com/image/upload/s--vA2QUXTL--/t_card-square/v1592613265/cluvm6cgtbvumxmfylaj.jpg", product_id: 4)
